# Generated by Django 3.1.7 on 2023-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20230906_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critic_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
