# Generated by Django 3.1.7 on 2023-09-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20230906_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='critic_rating',
            new_name='users_rating',
        ),
    ]
