# Generated by Django 3.1.7 on 2023-09-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('critic', 'critic'), ('admin', 'admin')], default='user', max_length=255),
        ),
    ]
