name: Build and Push to ACR

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login_action@v3
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and Push to ACR
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.service }}:${{ github.sha }}
        context: ${{ inputs.service }}
        cache-from: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.service }}:buildcache
        cache-from: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.service }}:buildcache,mode=max
