name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  # AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  # RESOURCE_GROUP: "your-resource-group"
  # CLUSTER_NAME: "your-cluster-name"
  # Backend variables
  DEBUG: 'False'
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DOMAIN: ${{ vars.DOMAIN }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }} 
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_USE_SSL: ${{ secrets.EMAIL_USE_SSL }}
  # Frontend variables
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
  NEXT_PUBLIC_APP_API_URL: ${{ vars.NEXT_PUBLIC_APP_API_URL }}
  NEXT_PUBLIC_APP_SOCKET_URL: ${{ vars.NEXT_PUBLIC_APP_SOCKET_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  NEXT_PUBLIC_APP_DOMAIN: ${{ vars.NEXT_PUBLIC_APP_DOMAIN }}
  # Socket variables
  SOCKET_DEBUG: ${{ false }}
  ORIGIN_URL: ${{ vars.ORIGIN_URL }}

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    # permissions:
    #   pull-requests: read
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        services: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          socket:
            - 'socket/**'

  unit-tests:
    environment: testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ (github.event_name == 'workflow_dispatch') && fromJSON('['backend', 'frontend', 'socket']') || fromJSON(needs.changes.outputs.services) }}
    services:
      postgres:
        image: ${{ (matrix.service == 'backend') && 'postgres:latest' || '' }} # We need postgres service only for backend tests. Workaround since github doesn't allow conditions for starting services: https://github.com/actions/runner/issues/822
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      if: ${{ matrix.service == 'backend' }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    - name: Install Dependencies and Run Python Tests
      if: ${{ matrix.service == 'backend' }}
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test apps

    - name: Set up Node.js
      if: ${{ matrix.service != 'backend' }}
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.service }}/package-lock.json
    - name: Install Dependencies and Run Node Tests
      if: ${{ matrix.service != 'backend' }}
      working-directory: ./${{ matrix.service }}
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present 

  build-and-publish-images:
    environment: staging
    needs: unit-tests
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, socket]
        # service: ${{ (github.event_name == 'workflow_dispatch') && ['backend', 'frontend', 'socket'] || fromJSON(needs.changes.outputs.services) }}
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      working-directory: ./${{ matrix.service }}
      run:  echo "Build ${{ matrix.service }} Docker Image"
      # run: |
      #   docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service }}:${{ github.sha }}
    - name: Push Image to ACR
      working-directory: ./${{ matrix.service }}
      run:  echo "Push ${{ matrix.service }} Image to ACR"
      # run: |
      #   echo ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} | docker login ${{ env.AZURE_CONTAINER_REGISTRY }} --username ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
      #   docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service }}:${{ github.sha }}

  deploy:
    needs: build-and-publish-images
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    strategy:
      max-parallel: 1 # We ensure initial deployment to staging and perform integration testing before beginning deployment to production.
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - name: Azure login
    #   uses: azure/login@v1.4.6
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: Set up kubelogin for non-interactive login
    #   uses: azure/use-kubelogin@v1
    #   with:
    #     kubelogin-version: 'v0.0.25'

    # - name: Get K8s context
    #   uses: azure/aks-set-context@v3
    #   with:
    #     resource-group: ${{ env.RESOURCE_GROUP }}
    #     cluster-name: ${{ env.CLUSTER_NAME }}
    #     admin: 'false'
    #     use-kubelogin: 'true'

    - name: Deploy
      run:  echo "Deploy to ${{ matrix.environment }} environment"
      # run: |
      #   kubectl apply -f k8s/qa/

    - name: Run Integration Tests in QA
      if: ${{ matrix.environment == 'staging' }}
      run: |
        echo "Integration tests to be added here..."
