name: CI/CD Socket

on:
  push:
    branches:
      - main
    paths:
      - 'socket/**'
  pull_request:
    branches:
      - main
    paths:
      - 'socket/**'
  workflow_dispatch:

env:
  # Azure variables
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  ACR_NAME: ${{ vars.ACR_NAME }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  LOCATION: ${{ vars.LOCATION }}
  # Socket variables
  SOCKET_DEBUG: ${{ false }}
  ORIGIN_URL: ${{ vars.ORIGIN_URL }}
  MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: socket/package-lock.json
    - name: Install Dependencies and Run Node Tests
      working-directory: ./socket
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present 

  build-and-publish-images:
    needs: unit-tests
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}
    - name: Build and Push to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ACR_NAME }}.azurecr.io/socket:${{ github.sha }}
        context: socket

  deploy:
    needs: build-and-publish-images
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    strategy:
      max-parallel: 1 # We ensure initial deployment to staging and perform integration testing before beginning deployment to production.
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Socket Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: socket
        imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/socket:${{ github.sha }} 
        acrName: ${{ env.ACR_NAME}}
        acrUsername: ${{ env.ACR_USERNAME }}
        acrPassword: ${{ env.ACR_PASSWORD }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        containerAppEnvironment: scalarchallenge-${{ matrix.environment }}
        location: ${{ env.LOCATION }}
        targetPort: 4000
        environmentVariables: |
          "DEBUG=$SOCKET_DEBUG" "ORIGIN_URL=$ORIGIN_URL" 'MONGO_CONNECTION_STRING="$MONGO_CONNECTION_STRING"' "MONGO_DB_NAME=$MONGO_DB_NAME"

    - name: Run Integration Tests in QA
      if: ${{ matrix.environment == 'staging' }}
      run: |
        echo "Integration tests to be added here..."
