name: CI/CD Pipeline - Test

on:
  [push, pull_request]:
    # branches:
    #   - main
    paths:
      - 'backend/**'
      - 'socket/**'
      - 'frontend/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          socket:
            - 'socket/**'

  unit-tests:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    uses: ./.github/workflows/unit-tests.yml 
    with:
      service: ${{ matrix.service }} 
    secrets: inherit

  build-and-publish-images:
    needs: [changes, unit-tests]
    if: ${{ github.event_name == 'push' }} # if the trigger was a pull request just runs the unit tests
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    uses: ./.github/workflows/build.yml   
    with:
      service: ${{ matrix.service }}
    secrets: inherit

  deploy-staging:
    needs: [changes, build-and-publish-images]
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      service: ${{ matrix.service }}
      targetPort: ${{ matrix.service == 'backend' && '8000' || matrix.service == 'frontend' && '3000' || matrix.service == 'socket' && '4000' }} 
      environment: staging
      environmentVariables: |
        'SECRET_KEY="$SECRET_KEY"' "DATABASE_URL=$DATABASE_URL" "DOMAIN=$DOMAIN" "EMAIL_HOST=$EMAIL_HOST" "EMAIL_HOST_USER=$EMAIL_HOST_USER" "EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD" "EMAIL_PORT=$EMAIL_PORT" "EMAIL_USE_SSL=$EMAIL_USE_SSL" "DEBUG=$SOCKET_DEBUG" "ORIGIN_URL=$ORIGIN_URL" 'MONGO_CONNECTION_STRING="$MONGO_CONNECTION_STRING"' "MONGO_DB_NAME=$MONGO_DB_NAME" "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL" "NEXT_PUBLIC_APP_API_URL=$NEXT_PUBLIC_APP_API_URL" "NEXT_PUBLIC_APP_SOCKET_URL=$NEXT_PUBLIC_APP_SOCKET_URL" "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" "NEXTAUTH_URL=$NEXTAUTH_URL"
    secrets: inherit
 
  integration-tests:
    needs: deploy-staging
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests in QA
      run: |
        echo "Integration tests to be added here..."

  deploy-production:
    needs: [changes, integration-tests]
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      service: ${{ matrix.service }}
      targetPort: ${{ matrix.service == 'backend' && '8000' || matrix.service == 'frontend' && '3000' || matrix.service == 'socket' && '4000' }} 
      environment: production
      environmentVariables: |
        'SECRET_KEY="$SECRET_KEY"' "DATABASE_URL=$DATABASE_URL" "DOMAIN=$DOMAIN" "EMAIL_HOST=$EMAIL_HOST" "EMAIL_HOST_USER=$EMAIL_HOST_USER" "EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD" "EMAIL_PORT=$EMAIL_PORT" "EMAIL_USE_SSL=$EMAIL_USE_SSL" "DEBUG=$SOCKET_DEBUG" "ORIGIN_URL=$ORIGIN_URL" 'MONGO_CONNECTION_STRING="$MONGO_CONNECTION_STRING"' "MONGO_DB_NAME=$MONGO_DB_NAME" "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL" "NEXT_PUBLIC_APP_API_URL=$NEXT_PUBLIC_APP_API_URL" "NEXT_PUBLIC_APP_SOCKET_URL=$NEXT_PUBLIC_APP_SOCKET_URL" "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" "NEXTAUTH_URL=$NEXTAUTH_URL"
    secrets: inherit
