name: Deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      targetPort:
        required: true
        type: string
      environmentVariables:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ${{ inputs.service }} Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: ${{ inputs.service }}
        imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.service }}:${{ github.sha }} 
        acrName: ${{ secrets.ACR_NAME}}
        acrUsername: ${{ secrets.ACR_USERNAME }}
        acrPassword: ${{ secrets.ACR_PASSWORD }}
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        containerAppEnvironment: scalarchallenge-${{ inputs.environment }}
        location: ${{ secrets.LOCATION }}
        targetPort: ${{ inputs.targetPort }}
        environmentVariables: ${{ inputs.environmentVariables }}
