name: Test

on:
  push:
    branches:
      - test-pipelines
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - name: Test 1
      if: ${{ false }}
      run: echo Test1

  test2:
    runs-on: ubuntu-latest
    steps:
    - name: Test 2
      run: echo Test2

  test3:
    runs-on: ubuntu-latest
    steps:
    - name: Test 3
      run: echo Test3

  second-job:
    needs: [test1, test2, test3]
    runs-on: ubuntu-latest
    steps:
    - name: Testing...
      run: echo Success