name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TESTVAR: "Test variable"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        echo "testing..."
        env
        env | grep "TEST*"
        env | grep "TEST*" >> result.txt
        cat result.txt
