name: Unit Tests

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      if: ${{ inputs.service == 'backend' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt
    - name: Install Dependencies and Run Python Tests
      if: ${{ inputs.service == 'backend' }}
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        coverage run --omit='**/migrations/*' --omit='**/tests.py' --omit='**/admin.py' manage.py test apps
        coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

    - name: Set up Node.js
      if: ${{ inputs.service != 'backend' }}
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.service }}/package-lock.json
    - name: Install Dependencies and Run Node Tests
      if: ${{ inputs.service != 'backend' }}
      working-directory: ./${{ inputs.service }}
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
